### ISSUE TITLE
Add a feature for rustls or just remove native-tls default

### ISSUE THREAD

**Issue by filiptibell** [cdriehuys/auth0-axum#37]
Hi, thank you for this great library!

We would like to use `reqwest` with the `rustls-tls` feature, but this library uses the default `native-tls` feature with no way to change it. For reference, axum itself removes the (default) native tls feature and lets the dependent choose how to enable it instead: https://github.com/tokio-rs/axum/blob/main/axum/Cargo.toml#L120

**Comment by cdriehuys** [comment]
Thanks for the suggestion! I don't have a ton of time to implement this, but I would happily accept a PR if you're able to make one.

**Comment by filiptibell** [comment]
> I would happily accept a PR if you're able to make one.

Sure thing! Here you go: https://github.com/cdriehuys/axum-jwks/pull/38

I took a look at some other crates such as [Sentry](https://github.com/getsentry/sentry-rust/blob/master/sentry/Cargo.toml) and organized the features in a similar way.
This is also semver-compatible (native tls is still default) so you won't have to bump the minor version.

Would you be able to cut a new release with this in the near-term future?
